### ISSUE TITLE
Add a collection name prefix in Typesense config

### ISSUE THREAD

**Issue by npotier** [acseo/TypesenseBundle#22]
In  case this bundle is used by mutliple projects and the same Typesense instance, it would be nice to have a prefix variable that would allow to have distinct collection names.

I had a issue once with two projects (staging and prod) on the same server. I'm thinking of somthing like this:

```yaml
# config/packages/acseo_typesense.yml
acseo_typesense:
    # Typesense host settings
    typesense:
        host: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
        collection_prefix: 'my-project-%env(resolve:APP_ENV)%-' #new optional value     
```   

as a result, for example, the collection `my-project-dev-books` would be created
