### ISSUE TITLE
"Call to a member function __toString() on null"

### ISSUE THREAD

**Issue by syl20b** [acseo/TypesenseBundle#52]
Hello, 
Thank you for your work ;)

When I execute the `bin/console typesense:import` command,  I've got the following error : `Call to a member function __toString() on null`

The publication attribute is nullable on my entity `App\Entity\Article`, and the field is declared as optional in my config. 

Here is a part of my config : 

```yaml
acseo_typesense:
  collections:
    articles:
      entity: 'App\Entity\Article'
      fields:

        publication:
          name: publication
          type: object
          facet: true
          optional: true

```

Is that a desired behaviour, or did I miss something ?

Sylvain
