### ISSUE TITLE
Warning: Undefined array key "scheme" 

### ISSUE THREAD

**Issue by DavidGodefroid** [acseo/TypesenseBundle#58]
Typesense is running in a typesense/typesense:0.23.1 Docker container and I've installed TypesenseBundle v0.6.7

```yaml
# config/package/acseo_typesense.yaml
acseo_typesense:
  # Typesense host settings
  typesense:
    url: '%env(resolve:TYPESENSE_URL)%'
    key: '%env(resolve:TYPESENSE_KEY)%'
  # Collection settings
  collections:
    faqs:                                   # Typesense collection name
      entity: 'App\Entity\Faq'              # Doctrine Entity class
      fields:
        #
        # Keeping Database and Typesense synchronized with ids
        #
        id:                                # Entity attribute name
          name: id                       # Typesense attribute name
          type: primary                  # Attribute type
        #
        # Using again id as a sortable field (int32 required)
        #
        sortable_id:
          entity_attribute: id             # Entity attribute name forced
          name: sortable_id                # Typesense field name
          type: int32
        title:
          name: title
          type: string
      default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float
```

When I run the `php bin/console typesense:create`, an error occurs: 

```bash
In TypesenseClient.php line 34:
Warning: Undefined array key "scheme"
```

Any idea?
