### ISSUE TITLE
Filter search object by category id

### ISSUE THREAD

**Issue by EvilSpartans** [acseo/TypesenseBundle#88]
Hello,

I am trying to find how can I filter search results in controller with something like category id (which is a manyToOne relation field) ?

For exemple If I used this in my controller : 

```
$queryPost = new TypesenseQuery($form->get('query')->getData(), 'title');
$posts = $this->postFinder->query($queryPost)->getResults();
```

Is it possible to get all $posts only where post.category == specific category id ? 

Actually my config file look this : 

```
        posts:                       
            entity: 'App\Entity\Post'    
            fields: 
                id:                   
                    name: id       
                    type: primary
                sortable_id:
                    entity_attribute: id
                    name: sortable_id
                    type: int32 
                title: 
                    name: title
                    type: string
                description:
                    name: description
                    type: string
                hashtag:
                    name: hashtag
                    type: string
            default_sorting_field: sortable_id 
```

Thanks for any help !
